import styled from '@emotion/styled'
import type { NextPage } from 'next'
import Head from 'next/head'
import ItemsTable from '../components/ItemsTable'
import Header from '../components/Header'
import TabNav from '../components/TabNav'
import { useNavigation } from '../context/NavigationContext'
import SearchInput from '../fragments/SearchInput'
import Sidebar from '../components/Sidebar'
import React from 'react'

const Home: NextPage = () => {
  const {tab} = useNavigation()
  
  return (
    <div style={{minHeight: '100vh'}}>
      <Head>
        <title>Pedido pago</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <MainContainer>
        <Sidebar />
        <div className="main">
          <h3 className="title">Organização</h3>
          <TableContainer>
            <TabNav />
            <SearchInput placeholder={tab === 'colaborators' ? 'Pesquise por nome ou cpf' : 'Pesquise por cargos'} />
            <ItemsTable />
          </TableContainer>
        </div>
      </MainContainer>
    </div>
  )
}

const MainContainer = styled.main`
  display: flex;
  max-width: 100vw;

  .main {
    padding: 0 14px;
    padding-top: 40px;
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    margin: 0 auto;
  }

  .title {
    font-weight: 600;
    font-size: 2rem;
    text-align: left;
    display: block;
  }
`
const TableContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  background-color:#FFFFFF;
  border-radius: 8px;
  padding: 24px;
  margin-top: 24px;

  width: 70vw;
`

export default Home
