import styled from '@emotion/styled'
import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import { useNavigation } from '../context/NavigationContext'
import SearchInput from '../fragments/SearchInput'
import Sidebar from '../components/Sidebar'
import React from 'react'
import dynamic from 'next/dynamic'

const TabNavtWithNoSSR = dynamic(
  () => import('../components/TabNav'),
  { ssr: false }
)
const DataContentWithNoSSR = dynamic(
  () => import('../components/DataContent'),
  { ssr: false }
)
const Home: NextPage = () => {
  const {tab} = useNavigation()
  
  return (
    <div style={{minHeight: '100vh'}}>
      <Head>
        <title>Pedido pago</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <MainContainer>
        <Sidebar />
        <div className="main">
          <h3 className="title">Organização</h3>
          <MainContent>
            <TabNavtWithNoSSR />
            <SearchInput placeholder={tab === 'colaborators' ? 'Pesquise por nome ou cpf' : 'Pesquise por cargos'} />
            <h4 className='list-title'>Listagem de {tab === 'colaborators' ? 'Colaboradores' : 'Cargos'}</h4>
            <DataContentWithNoSSR />
          </MainContent>
        </div>
      </MainContainer>
    </div>
  )
}

const MainContainer = styled.main`
  display: flex;
  max-width: 100vw;

  .main {
    padding: 0 14px;
    padding-top: 40px;
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    margin: 0 auto;
  }

  .title {
    font-weight: 600;
    font-size: 2rem;
    text-align: left;
    display: block;
  }
`
const MainContent = styled.div`
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  background-color:#FFFFFF;
  border-radius: 8px;
  padding: 24px;
  margin-top: 24px;

  width: 60vw;
  min-width: fit-content;
`

export default Home
